---
- name: Install Apache on Ubuntu and CentOS servers
  hosts: all
  become: yes
  tasks:
    - name: Install Apache on Ubuntu/Debian
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Apache on CentOS/RHEL
      yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure Apache service is enabled and started (Ubuntu)
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure Apache service is enabled and started (CentOS)
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_facts['os_family'] == "RedHat"



